# Generated by Django 2.2.6 on 2021-02-09 20:17

from django.db import migrations, models
import django.db.models.deletion
import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210111_0852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Выбирите группу, куда попадет пост', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.Group', validators=[posts.validators.validate_not_empty], verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Сделайте запись Вашего поста', verbose_name='Запись'),
        ),
    ]
