# Generated by Django 2.2.6 on 2021-02-17 07:20

from django.db import migrations, models
import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='Добавьте Ваш комментарий', validators=[posts.validators.validate_not_empty], verbose_name='Комментарий'),
        ),
    ]
